"""Audit action code constants — type-safe string constants for AuditLogger.log()."""


class AccionAuditoria:
    IMPERSONACION_INICIAR = "IMPERSONACION_INICIAR"
    IMPERSONACION_FINALIZAR = "IMPERSONACION_FINALIZAR"
    # C-06 estructura academica
    CARRERA_CREAR = "CARRERA_CREAR"
    CARRERA_ACTUALIZAR = "CARRERA_ACTUALIZAR"
    CARRERA_ELIMINAR = "CARRERA_ELIMINAR"
    MATERIA_CREAR = "MATERIA_CREAR"
    MATERIA_ACTUALIZAR = "MATERIA_ACTUALIZAR"
    MATERIA_ELIMINAR = "MATERIA_ELIMINAR"
    COHORTE_CREAR = "COHORTE_CREAR"
    COHORTE_ACTUALIZAR = "COHORTE_ACTUALIZAR"
    COHORTE_ELIMINAR = "COHORTE_ELIMINAR"
    DICTADO_CREAR = "DICTADO_CREAR"
    DICTADO_ACTUALIZAR = "DICTADO_ACTUALIZAR"
    DICTADO_ELIMINAR = "DICTADO_ELIMINAR"
    # C-07 usuarios y asignaciones
    USUARIO_CREAR = "USUARIO_CREAR"
    USUARIO_ACTUALIZAR = "USUARIO_ACTUALIZAR"
    USUARIO_ELIMINAR = "USUARIO_ELIMINAR"
    ASIGNACION_CREAR = "ASIGNACION_CREAR"
    ASIGNACION_ACTUALIZAR = "ASIGNACION_ACTUALIZAR"
    ASIGNACION_ELIMINAR = "ASIGNACION_ELIMINAR"
    # Forward-declared for future changes:
    CALIFICACIONES_IMPORTAR = "CALIFICACIONES_IMPORTAR"
    PADRON_CARGAR = "PADRON_CARGAR"
    COMUNICACION_ENVIAR = "COMUNICACION_ENVIAR"
    COMUNICACION_APROBAR = "COMUNICACION_APROBAR"
    ASIGNACION_MODIFICAR = "ASIGNACION_MODIFICAR"
    LIQUIDACION_CERRAR = "LIQUIDACION_CERRAR"
    # C-09 padron ingesta
    PADRON_VACIAR = "PADRON_VACIAR"
    # C-10 calificaciones y umbral
    UMBRAL_CONFIGURAR = "UMBRAL_CONFIGURAR"
    # C-11 analisis atrasados y reportes
    ANALISIS_ATRASADOS_CONSULTA = "ANALISIS_ATRASADOS_CONSULTA"
    ANALISIS_RANKING_CONSULTA = "ANALISIS_RANKING_CONSULTA"
    ANALISIS_REPORTE_CONSULTA = "ANALISIS_REPORTE_CONSULTA"
    ANALISIS_NOTAS_CONSULTA = "ANALISIS_NOTAS_CONSULTA"
    ANALISIS_TPS_CONSULTA = "ANALISIS_TPS_CONSULTA"
    ANALISIS_MONITOR_CONSULTA = "ANALISIS_MONITOR_CONSULTA"
