"""Audit action code constants — type-safe string constants for AuditLogger.log()."""


class AccionAuditoria:
    IMPERSONACION_INICIAR = "IMPERSONACION_INICIAR"
    IMPERSONACION_FINALIZAR = "IMPERSONACION_FINALIZAR"
    # C-06 estructura academica
    CARRERA_CREAR = "CARRERA_CREAR"
    CARRERA_ACTUALIZAR = "CARRERA_ACTUALIZAR"
    CARRERA_ELIMINAR = "CARRERA_ELIMINAR"
    MATERIA_CREAR = "MATERIA_CREAR"
    MATERIA_ACTUALIZAR = "MATERIA_ACTUALIZAR"
    MATERIA_ELIMINAR = "MATERIA_ELIMINAR"
    COHORTE_CREAR = "COHORTE_CREAR"
    COHORTE_ACTUALIZAR = "COHORTE_ACTUALIZAR"
    COHORTE_ELIMINAR = "COHORTE_ELIMINAR"
    DICTADO_CREAR = "DICTADO_CREAR"
    DICTADO_ACTUALIZAR = "DICTADO_ACTUALIZAR"
    DICTADO_ELIMINAR = "DICTADO_ELIMINAR"
    # C-34 admin toggle estado
    CARRERA_CAMBIAR_ESTADO = "CARRERA_CAMBIAR_ESTADO"
    MATERIA_CAMBIAR_ESTADO = "MATERIA_CAMBIAR_ESTADO"
    COHORTE_CAMBIAR_ESTADO = "COHORTE_CAMBIAR_ESTADO"
    DICTADO_CAMBIAR_ESTADO = "DICTADO_CAMBIAR_ESTADO"
    # C-07 usuarios y asignaciones
    USUARIO_CREAR = "USUARIO_CREAR"
    USUARIO_ACTUALIZAR = "USUARIO_ACTUALIZAR"
    USUARIO_ELIMINAR = "USUARIO_ELIMINAR"
    ASIGNACION_CREAR = "ASIGNACION_CREAR"
    ASIGNACION_ACTUALIZAR = "ASIGNACION_ACTUALIZAR"
    ASIGNACION_ELIMINAR = "ASIGNACION_ELIMINAR"
    # Forward-declared for future changes:
    CALIFICACIONES_IMPORTAR = "CALIFICACIONES_IMPORTAR"
    PADRON_CARGAR = "PADRON_CARGAR"
    COMUNICACION_ENVIAR = "COMUNICACION_ENVIAR"
    COMUNICACION_APROBAR = "COMUNICACION_APROBAR"
    ASIGNACION_MODIFICAR = "ASIGNACION_MODIFICAR"
    LIQUIDACION_CERRAR = "LIQUIDACION_CERRAR"
    # C-09 padron ingesta
    PADRON_VACIAR = "PADRON_VACIAR"
    # C-10 calificaciones y umbral
    UMBRAL_CONFIGURAR = "UMBRAL_CONFIGURAR"
    # C-11 analisis atrasados y reportes
    ANALISIS_ATRASADOS_CONSULTA = "ANALISIS_ATRASADOS_CONSULTA"
    ANALISIS_RANKING_CONSULTA = "ANALISIS_RANKING_CONSULTA"
    ANALISIS_REPORTE_CONSULTA = "ANALISIS_REPORTE_CONSULTA"
    ANALISIS_NOTAS_CONSULTA = "ANALISIS_NOTAS_CONSULTA"
    ANALISIS_TPS_CONSULTA = "ANALISIS_TPS_CONSULTA"
    ANALISIS_MONITOR_CONSULTA = "ANALISIS_MONITOR_CONSULTA"
    # C-13 encuentros y guardias
    ENCUENTRO_CREAR = "ENCUENTRO_CREAR"
    ENCUENTRO_EDITAR = "ENCUENTRO_EDITAR"
    ENCUENTRO_CANCELAR = "ENCUENTRO_CANCELAR"
    GUARDIA_REGISTRAR = "GUARDIA_REGISTRAR"
    # C-14 evaluaciones y coloquios
    COLOQUIO_CREAR = "COLOQUIO_CREAR"
    COLOQUIO_IMPORTAR_ALUMNOS = "COLOQUIO_IMPORTAR_ALUMNOS"
    COLOQUIO_RESERVAR = "COLOQUIO_RESERVAR"
    COLOQUIO_CANCELAR_RESERVA = "COLOQUIO_CANCELAR_RESERVA"
    COLOQUIO_REGISTRAR_RESULTADO = "COLOQUIO_REGISTRAR_RESULTADO"
    COLOQUIO_CERRAR = "COLOQUIO_CERRAR"
    # C-15 avisos y acknowledgment
    AVISO_CREAR = "AVISO_CREAR"
    AVISO_ACTUALIZAR = "AVISO_ACTUALIZAR"
    AVISO_ELIMINAR = "AVISO_ELIMINAR"
    AVISO_CONFIRMAR = "AVISO_CONFIRMAR"
    # C-16 tareas internas
    TAREA_CREAR = "TAREA_CREAR"
    TAREA_ACTUALIZAR = "TAREA_ACTUALIZAR"
    TAREA_ACTUALIZAR_ESTADO = "TAREA_ACTUALIZAR_ESTADO"
    TAREA_ELIMINAR = "TAREA_ELIMINAR"
    TAREA_COMENTAR = "TAREA_COMENTAR"
    # C-17 programas y fechas academicas
    PROGRAMA_CARGAR = "PROGRAMA_CARGAR"
    PROGRAMA_ACTUALIZAR = "PROGRAMA_ACTUALIZAR"
    PROGRAMA_ELIMINAR = "PROGRAMA_ELIMINAR"
    FECHA_ACADEMICA_CREAR = "FECHA_ACADEMICA_CREAR"
    FECHA_ACADEMICA_ACTUALIZAR = "FECHA_ACADEMICA_ACTUALIZAR"
    FECHA_ACADEMICA_ELIMINAR = "FECHA_ACADEMICA_ELIMINAR"
    # C-20 perfil y mensajeria interna
    PERFIL_ACTUALIZAR = "PERFIL_ACTUALIZAR"
    MENSAJE_RESPONDER = "MENSAJE_RESPONDER"
    # C-25 profesor dashboard
    CALIFICACION_EDITAR = "CALIFICACION_EDITAR"
    PADRON_ALUMNO_ALTA = "PADRON_ALUMNO_ALTA"
    PADRON_ALUMNO_BAJA = "PADRON_ALUMNO_BAJA"
